import { cookies } from "next/headers";
import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
import "./globals.css";

export const metadata = {
  title: "Nest - Multipurpose eCommerce HTML Template",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const data = await cookies();
  const cookie = data.get("token")?.value;
  const response = await fetch(
    "https://fdr-food-api.onrender.com/api/profile",
    {
      method: "GET",
      headers: {
        authorization: `Bearer ${cookie}`,
      },
    }
  );
  const res = await response.json();
  const userData = res.user;

  return (
    <html lang="en">
      <body
        data-new-gr-c-s-check-loaded="14.1250.0"
        data-gr-ext-installed={true}
      >
        <Navbar userData={userData} />
        {children}
        <Footer />
      </body>
    </html>
  );
}
